spring:
#  kafka:
#    bootstrap-servers: 194.87.244.66:9092
  datasource:
    url: jdbc:postgresql://localhost:5432/network
    username: postgres
    password: 123
  redis:
    host: localhost

logging:
  file:
    uploadLogs: false

auth:
  pass-restore: http://localhost:8080/change-password?token=
  email-restore: http://localhost:8080/shift-email?token=

